import{randomUUID}from"node:crypto";import type{Kysely}from"kysely";import type{BrokerAccountSnapshot,BrokerActivity,BrokerOrder,BrokerPosition}from"../../shared/broker";import type{Database}from"../db/types";import{mapBrokerActivity}from"./brokerActivityMapper";import{replayBrokerPortfolio}from"./brokerLedger";import{BrokerRepository}from"./brokerRepository";import type{ReconciliationRepository}from"./reconciliationService";
export class PostgresBrokerReconciliationRepository implements ReconciliationRepository{private orders:BrokerRepository;constructor(private database:Kysely<Database>,private now:()=>Date=()=>new Date()){this.orders=new BrokerRepository(database,now);}
 async saveSnapshot(account:BrokerAccountSnapshot,positions:BrokerPosition[],at:Date){await this.database.transaction().execute(async tx=>{await tx.insertInto("broker.account").values({id:account.accountId,status:account.status,currency:account.currency,createdAt:new Date(account.createdAt),updatedAt:at}).onConflict(c=>c.column("id").doUpdateSet({status:account.status,currency:account.currency,updatedAt:at})).execute();await tx.insertInto("broker.account_snapshot").values({id:randomUUID(),accountId:account.accountId,cash:account.cash,buyingPower:account.buyingPower,equity:account.equity,portfolioValue:account.portfolioValue,tradingBlocked:account.tradingBlocked,accountBlocked:account.accountBlocked,observedAt:new Date(account.observedAt)}).execute();await tx.deleteFrom("broker.position_snapshot").execute();if(positions.length)await tx.insertInto("broker.position_snapshot").values(positions.map(p=>({symbol:p.symbol,quantity:p.quantity,marketValue:p.marketValue,averageEntryPrice:p.averageEntryPrice,observedAt:at}))).execute();});}
 async observeOrder(order:BrokerOrder){const intent=await this.database.selectFrom("broker.order_intent").select("id").where("clientOrderId","=",order.clientOrderId).executeTakeFirst();if(!intent)return;await this.orders.bindRemoteOrder({intentId:intent.id,remoteOrderId:order.remoteOrderId,raw:order});await this.orders.appendOrderEvent({intentId:intent.id,event:`remote.${order.status}`,remoteEventId:`order:${order.remoteOrderId}:${order.status}:${order.updatedAt}`,payload:order,occurredAt:new Date(order.updatedAt)});}
 async ingestActivities(activities:BrokerActivity[]){for(const activity of activities){const event=mapBrokerActivity(activity);await this.orders.insertActivity({remoteActivityId:activity.remoteActivityId,type:activity.type,symbol:activity.symbol,amount:event.amount,quantity:event.quantity,price:event.price,occurredAt:new Date(activity.occurredAt),raw:activity.raw});await this.database.insertInto("broker.ledger_event").values({id:randomUUID(),remoteSourceId:event.remoteSourceId,eventType:event.eventType,symbol:event.symbol??null,quantity:event.eventType==="split"?(event.quantityMultiplier??null):(event.quantity??null),price:event.price??null,amount:event.amount??null,occurredAt:new Date(event.occurredAt),provenanceJson:JSON.stringify(event.provenance)}).onConflict(c=>c.column("remoteSourceId").doNothing()).execute();}}
 async replay(){const rows=await this.database.selectFrom("broker.ledger_event").selectAll().orderBy("occurredAt").orderBy("id").execute();return replayBrokerPortfolio(rows.map(r=>({remoteSourceId:r.remoteSourceId,eventType:r.eventType as never,symbol:r.symbol??undefined,quantity:r.quantity??undefined,price:r.price??undefined,amount:r.amount??undefined,quantityMultiplier:r.eventType==="split"?(r.quantity??undefined):undefined})));}
 async recordReconciliation(input:{status:"succeeded";at:Date;diagnostics:unknown}){const id=randomUUID();await this.database.insertInto("broker.reconciliation_run").values({id,status:input.status,diagnosticsJson:JSON.stringify(input.diagnostics),startedAt:input.at,finishedAt:input.at}).execute();return id;}
 async replaceDrift(input:{runId:string;cashDifference:string;symbolDifferences:{symbol:string;difference:string}[];at:Date}){await this.database.transaction().execute(async tx=>{await tx.updateTable("broker.drift").set({clearedAt:input.at}).where("clearedAt","is",null).execute();await tx.insertInto("broker.drift").values({id:randomUUID(),reconciliationRunId:input.runId,cashDifference:input.cashDifference,symbolDifferencesJson:JSON.stringify(input.symbolDifferences),detectedAt:input.at,clearedAt:null}).execute();});}
 async clearDrift(_runId:string,at:Date){await this.database.updateTable("broker.drift").set({clearedAt:at}).where("clearedAt","is",null).execute();}
}
