import type{Kysely}from"kysely";import type{Database}from"../db/types";
const json=<T>(value:unknown):T=>typeof value==="string"?JSON.parse(value)as T:value as T;
export class PostgresPaperPortfolioStore{constructor(private database:Kysely<Database>){}
 async getOverview(){const account=await this.database.selectFrom("broker.account_snapshot").selectAll().orderBy("observedAt","desc").executeTakeFirst();const positions=await this.database.selectFrom("broker.position_snapshot").selectAll().orderBy("symbol").execute();const drift=await this.database.selectFrom("broker.drift").selectAll().where("clearedAt","is",null).orderBy("detectedAt","desc").executeTakeFirst();return{account,positions,drift:drift?{cashDifference:drift.cashDifference??"0.00000000",symbolDifferences:json(drift.symbolDifferencesJson),detectedAt:drift.detectedAt.toISOString()}:undefined,asOf:account?.observedAt.toISOString()};}
 async listOrders(){return this.database.selectFrom("broker.order_intent as i").innerJoin("broker.order_projection as p","p.orderIntentId","i.id").leftJoin("broker.remote_order as r","r.orderIntentId","i.id").select(["i.id","i.clientOrderId","i.symbol","i.side","i.quantity","i.orderType","i.timeInForce","i.limitPrice","i.confirmedAt","p.state","p.updatedAt","r.remoteOrderId"]).orderBy("i.confirmedAt","desc").execute();}
 async getOrderTimeline(intentId:string){const rows=await this.database.selectFrom("broker.order_event").selectAll().where("orderIntentId","=",intentId).orderBy("occurredAt").orderBy("id").execute();return rows.map(row=>({...row,payloadJson:json(row.payloadJson)}));}
 async listActivities(){const rows=await this.database.selectFrom("broker.activity").selectAll().orderBy("occurredAt","desc").execute();return rows.map(row=>({...row,rawJson:json(row.rawJson)}));}
 async listLedger(){const rows=await this.database.selectFrom("broker.ledger_event").selectAll().orderBy("occurredAt").orderBy("id").execute();return rows.map(row=>({...row,provenanceJson:json(row.provenanceJson)}));}
}
