import { createHash,randomUUID } from "node:crypto"; import type { Kysely,Transaction } from "kysely"; import type { Database } from "../db/types"; import { ApiError } from "../core/errors"; import { browserMigrationDocumentSchema,migrationKeys,type BrowserMigrationDocument } from "./browserMigrationSchemas";
const canonical=(value:unknown):unknown=>Array.isArray(value)?value.map(canonical):value&&typeof value==="object"?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,canonical(v)])):value; const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex"); const value=(item:unknown)=>item as Record<string,any>; const date=(v:unknown,fallback:Date)=>typeof v==="string"?v:fallback;
export interface BrowserMigrationReceipt{id:string;documentHash:string;browserId:string;categoryCounts:Record<string,number>;categoryHashes:Record<string,string>;completedAt:string}
export class BrowserMigrationService { constructor(private readonly database:Kysely<Database>,private readonly now:()=>Date=()=>new Date()){}
 async preview(input:unknown){const document=this.validate(input);const receipt=await this.getReceipt(document.manifest.sha256);return{documentHash:document.manifest.sha256,totalValid:document.manifest.totalValid,totalQuarantined:document.manifest.totalQuarantined,targetEmpty:(await this.targetCount())===0,receipt};}
 async import(input:unknown):Promise<BrowserMigrationReceipt>{const document=this.validate(input);return this.database.transaction().execute(async tx=>{await tx.selectFrom("platform.installation").select("id").where("id","=","local-single-user").forUpdate().executeTakeFirstOrThrow();const existing=await tx.selectFrom("platform.browser_migration_receipt").selectAll().where("documentHash","=",document.manifest.sha256).executeTakeFirst();if(existing)return this.map(existing);if(await this.targetCount(tx)>0)throw new ApiError("MIGRATION_TARGET_NOT_EMPTY","服务端已有状态，不能自动导入",409,false);const counts:Record<string,number>={},hashes:Record<string,string>={};for(const category of migrationKeys){const source=document.categories[category];counts[category]=source.valid.length;hashes[category]=source.sha256;await this.importCategory(tx,category,source.valid);for(const[index,payloadJson]of source.valid.entries())await tx.insertInto("platform.browser_migration_record").values({category,ordinal:index,payloadJson:JSON.stringify(payloadJson)}).execute();}const imported=Number((await tx.selectFrom("platform.browser_migration_record").select(({fn})=>fn.countAll<string>().as("count")).executeTakeFirstOrThrow()).count);if(imported!==document.manifest.totalValid)throw new ApiError("MIGRATION_COUNT_MISMATCH","迁移后计数不匹配",500,false);const row=await tx.insertInto("platform.browser_migration_receipt").values({id:randomUUID(),documentHash:document.manifest.sha256,browserId:document.browserId,categoryCountsJson:JSON.stringify(counts),categoryHashesJson:JSON.stringify(hashes),completedAt:this.now()}).returningAll().executeTakeFirstOrThrow();return this.map(row);});}
 async latestReceipt():Promise<BrowserMigrationReceipt|undefined>{const row=await this.database.selectFrom("platform.browser_migration_receipt").selectAll().orderBy("completedAt","desc").executeTakeFirst();return row?this.map(row):undefined;}
 private async importCategory(tx:Transaction<Database>,category:string,records:unknown[]){const now=this.now();for(const raw of records){const x=value(raw);
  if(category==="stock_m:user-universe:v1"){for(const symbol of x.addedSymbols??[])await tx.insertInto("core.user_universe_symbol").values({symbol:String(symbol).toUpperCase(),kind:"added",createdAt:now}).onConflict(c=>c.column("symbol").doNothing()).execute();for(const symbol of x.removedDefaultSymbols??[])await tx.insertInto("core.user_universe_symbol").values({symbol:String(symbol).toUpperCase(),kind:"removed_default",createdAt:now}).onConflict(c=>c.column("symbol").doNothing()).execute();await tx.updateTable("core.user_universe_revision").set({version:Number(x.version??0)}).where("id","=","local-single-user").execute();}
  if(category==="stock_m:saved-screens:v1")await tx.insertInto("core.saved_screen").values({id:x.id,name:x.name,conditionsJson:JSON.stringify(x.conditions??[]),sortMetric:x.sort?.metric??x.sortMetric,sortDirection:x.sort?.direction??x.sortDirection??"desc",version:Number(x.version??1),createdAt:date(x.createdAt,now),updatedAt:date(x.updatedAt,now),deletedAt:x.deletedAt??null}).execute();
  if(category==="stock_m:watchlists:v1"){await tx.insertInto("core.watchlist_group").values({id:x.id,name:x.name,orderIndex:Number(x.order??x.orderIndex??0),version:Number(x.version??1),createdAt:date(x.createdAt,now),updatedAt:date(x.updatedAt,now),deletedAt:x.deletedAt??null}).execute();for(const[index,symbol]of(x.symbols??[]).entries())await tx.insertInto("core.watchlist_symbol").values({groupId:x.id,symbol:String(symbol).toUpperCase(),orderIndex:index,createdAt:date(x.createdAt,now)}).execute();}
  if(category==="stock_m:theses")await tx.insertInto("core.thesis_version").values({id:x.id,symbol:String(x.symbol).toUpperCase(),version:Number(x.version),coreJudgment:x.coreJudgment,evidenceJson:JSON.stringify(x.evidence??[]),risksJson:JSON.stringify(x.risks??[]),validationConditionsJson:JSON.stringify(x.validationConditions??[]),createdAt:date(x.createdAt,now)}).execute();
  if(category==="stock_m:thesis-conditions:v1")await tx.insertInto("core.thesis_condition").values({id:x.id,thesisVersionId:x.thesisVersionId,symbol:String(x.symbol).toUpperCase(),kind:x.kind,name:x.name,direction:x.direction,severity:x.severity,deadline:x.deadline??null,note:x.note??null,specJson:JSON.stringify(x),conditionVersion:x.conditionVersion,createdAt:date(x.createdAt,now),updatedAt:date(x.updatedAt,now),deletedAt:x.deletedAt??null}).execute();
  if(category==="stock_m:condition-evaluations:v1"){const dedupeKey=`${x.conditionId}:${x.conditionVersion}:${x.dataState}:${x.status}:${x.asOf??""}`;await tx.insertInto("monitor.condition_evaluation").values({id:x.id,conditionId:x.conditionId,conditionVersion:x.conditionVersion,dedupeKey,status:x.status,dataState:x.dataState,actualValueJson:x.actualValue===undefined?null:JSON.stringify(x.actualValue),targetValueJson:x.targetValue===undefined?null:JSON.stringify(x.targetValue),source:x.source??null,asOf:x.asOf??null,explanation:x.explanation,evaluatedAt:date(x.evaluatedAt,now),changed:Boolean(x.changed),previousStatus:x.previousStatus??null}).execute();}
  if(category==="stock_m:monitor-alerts:v1"){await tx.insertInto("monitor.alert").values({id:x.id,dedupeKey:x.dedupeKey,symbol:String(x.symbol).toUpperCase(),thesisVersionId:x.thesisVersionId,conditionId:x.conditionId,conditionVersion:x.conditionVersion,fromStatus:x.fromStatus??null,toStatus:x.toStatus,severity:x.severity,title:x.title,explanation:x.explanation,asOf:x.asOf??null,createdAt:date(x.createdAt,now)}).execute();for(const [type,at,until]of [["read",x.readAt,null],["snooze",x.snoozedUntil,x.snoozedUntil],["archive",x.archivedAt,null]]as const)if(at)await tx.insertInto("monitor.alert_action").values({id:randomUUID(),alertId:x.id,type,untilAt:until,createdAt:at}).execute();}
  if(category==="stock_m:thesis-reviews:v1")await tx.insertInto("monitor.thesis_review").values({id:x.id,thesisVersionId:x.thesisVersionId,symbol:String(x.symbol).toUpperCase(),decision:x.decision,note:x.note??null,conditionSnapshotJson:JSON.stringify(x.conditionSnapshot??[]),createdAt:date(x.createdAt,now)}).execute();
  if(category==="stock_m:portfolio-ledger:v1")await tx.insertInto("core.manual_portfolio_ledger_event").values({id:x.id,portfolioId:"default",type:x.type,symbol:x.symbol??null,occurredAt:date(x.occurredAt,now),quantity:x.quantity??null,price:x.price??null,amount:x.amount??null,thesisVersionId:x.thesisVersionId??null,reason:x.reason??null,oldRate:x.oldRate??null,newRate:x.newRate??null,quantityMultiplier:x.quantityMultiplier??null,source:x.source??null,sourceEventId:x.sourceEventId??null,confirmedAt:x.confirmedAt??null}).execute();
  if(category==="stock_m:portfolio-settings:v1")await tx.updateTable("core.manual_portfolio_settings").set({initialCash:Number(x.initialCash),inceptionDate:x.inceptionDate,benchmarkSymbol:x.benchmarkSymbol,updatedAt:date(x.updatedAt,now)}).where("portfolioId","=","default").execute();
  if(category==="stock_m:ignored-splits:v1")await tx.insertInto("core.manual_portfolio_ignored_split").values({portfolioId:"default",sourceEventId:x.sourceEventId,symbol:x.symbol,note:x.note,ignoredAt:date(x.ignoredAt,now)}).execute();
  if(category==="stock_m:portfolio-alerts:v1"){await tx.insertInto("core.portfolio_alert").values({id:x.id,portfolioId:"default",dedupeKey:x.dedupeKey,rule:x.rule,severity:x.severity,symbol:x.symbol??null,message:x.message,currentValueJson:JSON.stringify(x.currentValue),thresholdJson:JSON.stringify(x.threshold),createdAt:date(x.createdAt,now)}).execute();if(x.status==="snoozed")await tx.insertInto("core.portfolio_alert_action").values({id:randomUUID(),alertId:x.id,type:"snooze",untilAt:x.snoozedUntil,createdAt:date(x.updatedAt,now)}).execute();if(x.status==="resolved")await tx.insertInto("core.portfolio_alert_action").values({id:randomUUID(),alertId:x.id,type:"resolve",untilAt:null,createdAt:date(x.resolvedAt??x.updatedAt,now)}).execute();}
  if(category==="stock_m:portfolio-snapshots:v1")await tx.insertInto("core.portfolio_snapshot").values({id:x.id,portfolioId:"default",asOf:date(x.asOf,now),snapshotJson:JSON.stringify(x),createdAt:date(x.asOf,now)}).execute();
  if(category==="stock_m:portfolio-reviews:v1")await tx.insertInto("core.portfolio_weekly_review").values({id:x.id,portfolioId:"default",week:x.week,version:Number(x.version),snapshotId:x.snapshotId,judgment:x.judgment,action:x.action,result:x.result,nextObservationsJson:JSON.stringify(x.nextObservations??[]),tradeCount:Number(x.summary?.tradeCount??0),openAlertCount:Number(x.summary?.openAlertCount??0),createdAt:date(x.createdAt,now)}).execute();
 }}
 private async targetCount(executor:Kysely<Database>|Transaction<Database>=this.database){const tables=["core.user_universe_symbol","core.saved_screen","core.watchlist_group","core.thesis_version","core.thesis_condition","monitor.condition_evaluation","monitor.alert","monitor.thesis_review","core.manual_portfolio_ledger_event","core.manual_portfolio_ignored_split","core.portfolio_alert","core.portfolio_snapshot","core.portfolio_weekly_review"]as const;let total=0;for(const table of tables)total+=Number((await executor.selectFrom(table).select(({fn})=>fn.countAll<string>().as("count")).executeTakeFirstOrThrow()).count);return total;}
 private getReceipt(documentHash:string){return this.database.selectFrom("platform.browser_migration_receipt").selectAll().where("documentHash","=",documentHash).executeTakeFirst().then(row=>row?this.map(row):undefined);} private validate(input:unknown):BrowserMigrationDocument{const parsed=browserMigrationDocumentSchema.safeParse(input);if(!parsed.success)throw new ApiError("INVALID_MIGRATION_DOCUMENT",parsed.error.issues[0]?.message??"迁移文档无效",400,false);const document=parsed.data;let totalValid=0,totalQuarantined=0;for(const category of migrationKeys){const entry=document.categories[category];if(hash({valid:entry.valid,quarantined:entry.quarantined})!==entry.sha256)throw new ApiError("MIGRATION_HASH_MISMATCH","迁移分类摘要不匹配",400,false);totalValid+=entry.valid.length;totalQuarantined+=entry.quarantined.length;}const{manifest,...base}=document;if(hash(base)!==manifest.sha256)throw new ApiError("MIGRATION_HASH_MISMATCH","迁移文档摘要不匹配",400,false);if(totalValid!==manifest.totalValid||totalQuarantined!==manifest.totalQuarantined)throw new ApiError("MIGRATION_COUNT_MISMATCH","迁移分类计数不匹配",400,false);return document;} private map(row:any):BrowserMigrationReceipt{return{id:row.id,documentHash:row.documentHash,browserId:row.browserId,categoryCounts:row.categoryCountsJson,categoryHashes:row.categoryHashesJson,completedAt:row.completedAt.toISOString()};}
}
