import { randomUUID } from "node:crypto"; import type { FastifyInstance,FastifyReply,FastifyRequest } from "fastify"; import type { Kysely,Transaction } from "kysely"; import { z } from "zod";
import type { AlertCandidate,IgnoredSplitDecision,LedgerEventInput,PortfolioAlertActionInput,PortfolioSettings,WeeklyReviewInput } from "../../shared/portfolio"; import { ApiError } from "../core/errors"; import type { Database } from "../db/types"; import type { PostgresManualPortfolioRepository } from "../portfolio/manualPortfolioRepository"; import type { PostgresPortfolioReviewRepository } from "../portfolio/portfolioReviewRepository"; import type { IdempotencyStore,StoredHttpResponse } from "../platform/idempotencyRepository"; import type { OutboxRepository } from "../platform/outboxRepository"; import { withIdempotency } from "../platform/withIdempotency";
export interface ManualPortfolioRouteDependencies { database:Kysely<Database>;idempotency:IdempotencyStore;outbox:Pick<OutboxRepository,"append">;repository:PostgresManualPortfolioRepository;reviews:PostgresPortfolioReviewRepository }
const ledger=z.object({type:z.enum(["buy","sell","dividend","fee","deposit","withdrawal","split"]),occurredAt:z.string().datetime()}).passthrough(); const settings=z.object({initialCash:z.number().positive(),inceptionDate:z.string(),benchmarkSymbol:z.string().min(1),baseCurrency:z.literal("USD")}); const split=z.object({sourceEventId:z.string().min(1),symbol:z.string().min(1),note:z.string(),ignoredAt:z.string().datetime()}); const review=z.object({week:z.string().min(1),snapshot:z.record(z.string(),z.unknown()),events:z.array(z.unknown()),alerts:z.array(z.unknown()),judgment:z.string(),action:z.string(),result:z.string(),nextObservations:z.array(z.string())}); const idSchema=z.object({id:z.string().min(1)}); const week=z.object({week:z.string().optional()}); const alertAction=z.discriminatedUnion("type",[z.object({type:z.literal("acknowledge")}),z.object({type:z.literal("resolve")}),z.object({type:z.literal("snooze"),until:z.string().datetime()})]); const candidates=z.object({candidates:z.array(z.object({dedupeKey:z.string(),rule:z.string(),severity:z.enum(["info","warning","critical"]),symbol:z.string().optional(),message:z.string(),currentValue:z.union([z.number(),z.string()]),threshold:z.union([z.number(),z.string()])}))});
function parse<T>(schema:z.ZodType<T>,value:unknown):T{const parsed=schema.safeParse(value);if(!parsed.success)throw new ApiError("INVALID_REQUEST",parsed.error.issues[0]?.message??"请求无效",400,false);return parsed.data;}
async function mutate<T>(d:ManualPortfolioRouteDependencies,req:FastifyRequest,reply:FastifyReply,o:{route:string;body:unknown;topic:string;aggregateId:string},fn:(tx:Transaction<Database>)=>Promise<T>){const response=await withIdempotency({database:d.database,store:d.idempotency},{key:req.headers["idempotency-key"]as string,route:o.route,body:o.body},async(tx):Promise<StoredHttpResponse>=>{const value=await fn(tx);await d.outbox.append(tx,{id:randomUUID(),topic:o.topic,aggregateId:o.aggregateId,payloadJson:value??{ok:true},occurredAt:new Date()});return{statusCode:201,body:value};});return reply.status(response.statusCode).send(response.body);}
export function registerManualPortfolioRoutes(app:FastifyInstance,d:ManualPortfolioRouteDependencies):void{
 app.get("/api/v1/portfolio/bootstrap",()=>d.repository.getBootstrap()); app.put("/api/v1/portfolio/settings",async(req,reply)=>{const body=parse(settings,req.body)as Omit<PortfolioSettings,"version"|"updatedAt">;return mutate(d,req,reply,{route:"PUT /api/v1/portfolio/settings",body,topic:"portfolio.settings.changed",aggregateId:"default"},tx=>d.repository.saveSettings(body,tx));});
 app.post("/api/v1/portfolio/ledger-events",async(req,reply)=>{const body=parse(ledger,req.body)as LedgerEventInput;return mutate(d,req,reply,{route:"POST /api/v1/portfolio/ledger-events",body,topic:"portfolio.ledger-event.created",aggregateId:"default"},tx=>d.repository.append(body,tx));}); app.post("/api/v1/portfolio/ignored-splits",async(req,reply)=>{const body=parse(split,req.body)as IgnoredSplitDecision;return mutate(d,req,reply,{route:"POST /api/v1/portfolio/ignored-splits",body,topic:"portfolio.split.ignored",aggregateId:body.sourceEventId},tx=>d.repository.ignoreSplit(body,tx));});
 app.post("/api/v1/portfolio/alerts/reconcile",async(req,reply)=>{const body=parse(candidates,req.body);return mutate(d,req,reply,{route:"POST /api/v1/portfolio/alerts/reconcile",body,topic:"portfolio.alerts.reconciled",aggregateId:"default"},tx=>d.repository.reconcileAlerts(body.candidates as AlertCandidate[],tx));}); app.post("/api/v1/portfolio/alerts/:id/actions",async(req,reply)=>{const {id}=parse(idSchema,req.params);const body=parse(alertAction,req.body)as PortfolioAlertActionInput;return mutate(d,req,reply,{route:"POST /api/v1/portfolio/alerts/:id/actions",body:{id,...body},topic:"portfolio.alert.action.created",aggregateId:id},tx=>d.repository.actAlert(id,body,tx));});
 app.get("/api/v1/portfolio/reviews",req=>d.reviews.list(parse(week,req.query).week)); app.post("/api/v1/portfolio/reviews",async(req,reply)=>{const body=parse(review,req.body)as unknown as WeeklyReviewInput;return mutate(d,req,reply,{route:"POST /api/v1/portfolio/reviews",body,topic:"portfolio.review.created",aggregateId:body.week},tx=>d.reviews.submit(body,tx));}); app.get("/api/v1/portfolio/snapshots/:id",req=>d.reviews.getSnapshot(parse(idSchema,req.params).id));
}
