import { randomUUID } from "node:crypto";
import type { Kysely, Transaction } from "kysely";
import type { AlertCandidate, IgnoredSplitDecision, LedgerEvent, LedgerEventInput, PortfolioAlert, PortfolioAlertActionInput, PortfolioBootstrap, PortfolioSettings } from "../../shared/portfolio";
import { ApiError } from "../core/errors";
import type { Database } from "../db/types";
type Executor = Transaction<Database>; const id = "default"; const n = (value: string|null) => value === null ? undefined : Number(value);
export class PostgresManualPortfolioRepository {
  constructor(private readonly database: Kysely<Database>, private readonly now:()=>Date=()=>new Date()) {}
  async getBootstrap(): Promise<PortfolioBootstrap> { return this.database.transaction().setIsolationLevel("repeatable read").execute(async (tx) => { const portfolio=await tx.selectFrom("core.manual_portfolio").select("revision").where("id","=",id).executeTakeFirstOrThrow(); const reviewRows=await tx.selectFrom("core.portfolio_weekly_review").selectAll().where("portfolioId","=",id).orderBy("week","asc").orderBy("version","asc").execute(); const reviews=reviewRows.map(r=>({id:r.id,week:r.week,version:r.version,snapshotId:r.snapshotId,judgment:r.judgment,action:r.action,result:r.result,nextObservations:r.nextObservationsJson as string[],createdAt:r.createdAt.toISOString(),summary:{tradeCount:r.tradeCount,openAlertCount:r.openAlertCount}})); return { revision:portfolio.revision, settings:await this.getSettings(tx), events:await this.listLedger(tx), ignoredSplits:await this.listIgnored(tx), alerts:await this.listAlerts(tx), reviews }; }); }
  async getSettings(executor:Kysely<Database>|Executor=this.database):Promise<PortfolioSettings>{ const row=await executor.selectFrom("core.manual_portfolio_settings").selectAll().where("portfolioId","=",id).executeTakeFirstOrThrow(); return { version:1, initialCash:Number(row.initialCash), inceptionDate:row.inceptionDate, benchmarkSymbol:row.benchmarkSymbol, baseCurrency:"USD", updatedAt:row.updatedAt.toISOString() }; }
  saveSettings(input:Omit<PortfolioSettings,"version"|"updatedAt">, executor?:Executor):Promise<PortfolioSettings>{ return this.tx(executor,async tx=>{ await this.lock(tx); const now=this.now(); await tx.updateTable("core.manual_portfolio_settings").set({initialCash:input.initialCash,inceptionDate:input.inceptionDate,benchmarkSymbol:input.benchmarkSymbol.toUpperCase(),updatedAt:now}).where("portfolioId","=",id).execute(); await this.bump(tx); return this.getSettings(tx); }); }
  async listLedger(executor:Kysely<Database>|Executor=this.database):Promise<LedgerEvent[]>{ const rows=await executor.selectFrom("core.manual_portfolio_ledger_event").selectAll().where("portfolioId","=",id).orderBy("ordinal","asc").execute(); return rows.map(row=>({id:row.id,type:row.type,occurredAt:row.occurredAt.toISOString(),...(row.symbol?{symbol:row.symbol}:{}),...(n(row.quantity)!==undefined?{quantity:n(row.quantity)}:{}),...(n(row.price)!==undefined?{price:n(row.price)}:{}),...(n(row.amount)!==undefined?{amount:n(row.amount)}:{}),...(row.thesisVersionId?{thesisVersionId:row.thesisVersionId}:{}),...(row.reason?{reason:row.reason}:{}),...(n(row.oldRate)!==undefined?{oldRate:n(row.oldRate)}:{}),...(n(row.newRate)!==undefined?{newRate:n(row.newRate)}:{}),...(n(row.quantityMultiplier)!==undefined?{quantityMultiplier:n(row.quantityMultiplier)}:{}),...(row.source?{source:row.source}:{}),...(row.sourceEventId?{sourceEventId:row.sourceEventId}:{}),...(row.confirmedAt?{confirmedAt:row.confirmedAt.toISOString()}:{})})); }
  append(input:LedgerEventInput, executor?:Executor):Promise<LedgerEvent>{ return this.tx(executor,async tx=>{ await this.lock(tx); this.validate(input); if(input.type==="split"){ const found=await tx.selectFrom("core.manual_portfolio_ledger_event").selectAll().where("sourceEventId","=",input.sourceEventId!).executeTakeFirst(); if(found) return (await this.listLedger(tx)).find(x=>x.id===found.id)!; }
    const events=await this.listLedger(tx); const quantity=(symbol:string)=>events.filter(e=>e.symbol===symbol).reduce((q,e)=>e.type==="buy"?q+(e.quantity??0):e.type==="sell"?q-(e.quantity??0):e.type==="split"?q*(e.quantityMultiplier??1):q,0); const settings=await this.getSettings(tx); const cash=events.filter(e=>e.occurredAt<=input.occurredAt).reduce((c,e)=>e.type==="buy"?c-(e.quantity??0)*(e.price??0):e.type==="sell"?c+(e.quantity??0)*(e.price??0):e.type==="dividend"||e.type==="deposit"?c+(e.amount??0):e.type==="fee"||e.type==="withdrawal"?c-(e.amount??0):c,settings.initialCash);
    if(input.type==="sell"&&(input.quantity??0)>quantity(input.symbol!)) throw new ApiError("INSUFFICIENT_QUANTITY",`可卖数量为 ${quantity(input.symbol!)}`,409,false); if(input.type==="withdrawal"&&(input.amount??0)>cash) throw new ApiError("INSUFFICIENT_CASH",`可用现金为 ${cash}`,409,false);
    const eventId=randomUUID(); await tx.insertInto("core.manual_portfolio_ledger_event").values({id:eventId,portfolioId:id,type:input.type,symbol:input.symbol?.toUpperCase()??null,occurredAt:input.occurredAt,quantity:input.quantity??null,price:input.price??null,amount:input.amount??null,thesisVersionId:input.thesisVersionId??null,reason:input.reason??null,oldRate:input.oldRate??null,newRate:input.newRate??null,quantityMultiplier:input.quantityMultiplier??null,source:input.source??null,sourceEventId:input.sourceEventId??null,confirmedAt:input.confirmedAt??null}).execute(); await this.bump(tx); return (await this.listLedger(tx)).find(e=>e.id===eventId)!; }); }
  ignoreSplit(decision:IgnoredSplitDecision, executor?:Executor):Promise<IgnoredSplitDecision>{return this.tx(executor,async tx=>{await this.lock(tx);await tx.insertInto("core.manual_portfolio_ignored_split").values({portfolioId:id,...decision}).onConflict(c=>c.column("sourceEventId").doNothing()).execute();await this.bump(tx);return (await this.listIgnored(tx)).find(x=>x.sourceEventId===decision.sourceEventId)!;});}
  async listIgnored(executor:Kysely<Database>|Executor=this.database):Promise<IgnoredSplitDecision[]>{const rows=await executor.selectFrom("core.manual_portfolio_ignored_split").selectAll().where("portfolioId","=",id).orderBy("ignoredAt","asc").execute();return rows.map(r=>({sourceEventId:r.sourceEventId,symbol:r.symbol,note:r.note,ignoredAt:r.ignoredAt.toISOString()}));}
  reconcileAlerts(candidates:AlertCandidate[],executor?:Executor):Promise<PortfolioAlert[]>{return this.tx(executor,async tx=>{await this.lock(tx);for(const candidate of candidates){await tx.insertInto("core.portfolio_alert").values({id:randomUUID(),portfolioId:id,dedupeKey:candidate.dedupeKey,rule:candidate.rule,severity:candidate.severity,symbol:candidate.symbol??null,message:candidate.message,currentValueJson:JSON.stringify(candidate.currentValue),thresholdJson:JSON.stringify(candidate.threshold),createdAt:this.now()}).onConflict(c=>c.column("dedupeKey").doNothing()).execute();}await this.bump(tx);return this.listAlerts(tx);});}
  async listAlerts(executor:Kysely<Database>|Executor=this.database):Promise<PortfolioAlert[]>{const rows=await executor.selectFrom("core.portfolio_alert").selectAll().where("portfolioId","=",id).orderBy("createdAt","asc").execute();return Promise.all(rows.map(async row=>{const actions=await executor.selectFrom("core.portfolio_alert_action").selectAll().where("alertId","=",row.id).orderBy("ordinal","asc").execute();let status:"open"|"snoozed"|"resolved"="open",snoozedUntil:string|undefined,resolvedAt:string|undefined,updatedAt=row.createdAt.toISOString();for(const action of actions){updatedAt=action.createdAt.toISOString();if(action.type==="snooze"){status="snoozed";snoozedUntil=action.untilAt?.toISOString();}if(action.type==="resolve"){status="resolved";resolvedAt=updatedAt;}if(action.type==="acknowledge")status="open";}return{id:row.id,dedupeKey:row.dedupeKey,rule:row.rule,severity:row.severity,symbol:row.symbol??undefined,message:row.message,currentValue:row.currentValueJson as number|string,threshold:row.thresholdJson as number|string,status,createdAt:row.createdAt.toISOString(),updatedAt,...(snoozedUntil?{snoozedUntil}:{}),...(resolvedAt?{resolvedAt}:{})};}));}
  actAlert(alertId:string,action:PortfolioAlertActionInput,executor?:Executor):Promise<PortfolioAlert>{return this.tx(executor,async tx=>{await this.lock(tx);const exists=await tx.selectFrom("core.portfolio_alert").select("id").where("id","=",alertId).executeTakeFirst();if(!exists)throw new ApiError("PORTFOLIO_ALERT_NOT_FOUND","未找到组合提醒",404,false);await tx.insertInto("core.portfolio_alert_action").values({id:randomUUID(),alertId,type:action.type,untilAt:action.type==="snooze"?action.until:null,createdAt:this.now()}).execute();await this.bump(tx);return(await this.listAlerts(tx)).find(a=>a.id===alertId)!;});}
  private validate(i:LedgerEventInput){if(Number.isNaN(Date.parse(i.occurredAt)))throw new ApiError("INVALID_LEDGER_EVENT","发生时间无效",400,false);if((i.type==="buy"||i.type==="sell")&&(!(i.quantity!>0)||!(i.price!>0)))throw new ApiError("INVALID_LEDGER_EVENT","数量和价格必须大于零",400,false);if(i.type==="buy"&&!i.thesisVersionId)throw new ApiError("INVALID_LEDGER_EVENT","买入必须关联投资逻辑",400,false);if(i.type==="split"&&(!i.sourceEventId||!(i.oldRate!>0)||!(i.newRate!>0)||!(i.quantityMultiplier!>0)))throw new ApiError("INVALID_LEDGER_EVENT","拆股信息无效",400,false);if(!["buy","sell","split"].includes(i.type)&&(!(i.amount!>0)||!i.reason?.trim()))throw new ApiError("INVALID_LEDGER_EVENT","金额和原因无效",400,false);}
  private async lock(tx:Executor){await tx.selectFrom("core.manual_portfolio").select("id").where("id","=",id).forUpdate().executeTakeFirstOrThrow();} private bump(tx:Executor){return tx.updateTable("core.manual_portfolio").set(({eb})=>({revision:eb("revision","+",1)})).where("id","=",id).execute();} private tx<T>(executor:Executor|undefined,fn:(tx:Executor)=>Promise<T>):Promise<T>{return executor?fn(executor):this.database.transaction().execute(fn);}
}
