import{randomUUID}from"node:crypto";import type{AlpacaTradingPort,BrokerAccountSnapshot,BrokerActivity,BrokerAsset,BrokerOrder,BrokerPosition,PaperOrderRequest}from"../../shared/broker";import{BrokerProviderError}from"../broker/alpacaTradingProvider";
export class FakeAlpacaTradingProvider implements AlpacaTradingPort{private orders=new Map<string,BrokerOrder>();private activities:BrokerActivity[]=[];private positions=new Map<string,{quantity:number,cost:number}>();private lost=false;private cancelPending=new Set<string>();private cash=10000;private tick=0;private timestamp(){return new Date(Date.UTC(2026,7,11,14,0,this.tick++)).toISOString();}
 constructor(){this.reset();}failNextSubmitAsLostResponse(){this.lost=true;}reset(){this.orders.clear();this.positions.clear();this.cancelPending.clear();this.cash=10000;this.lost=false;this.activities=[{remoteActivityId:"fixture-opening-cash",type:"CSD",occurredAt:"2026-08-01T00:00:00Z",amount:"10000",raw:{fixture:true}}];}
 setCash(value:number){this.cash=value;}
 async getAccount():Promise<BrokerAccountSnapshot>{const observedAt=this.timestamp();return{accountId:"fixture-paper",status:"ACTIVE",currency:"USD",cash:this.cash.toFixed(8),buyingPower:this.cash.toFixed(8),equity:this.cash.toFixed(8),portfolioValue:this.cash.toFixed(8),tradingBlocked:false,accountBlocked:false,createdAt:"2026-08-01T00:00:00Z",observedAt};}
 async getAsset(symbol:string):Promise<BrokerAsset>{return{assetId:`asset-${symbol}`,assetClass:"us_equity",exchange:"NASDAQ",symbol:symbol.toUpperCase(),status:"active",tradable:true,fractionable:true};}
 async getPosition(symbol:string){return(await this.listPositions()).find(p=>p.symbol===symbol.toUpperCase());}
 async listPositions():Promise<BrokerPosition[]>{return[...this.positions].filter(([,p])=>p.quantity!==0).map(([symbol,p])=>({symbol,quantity:p.quantity.toFixed(8),marketValue:p.cost.toFixed(8),averageEntryPrice:(p.cost/p.quantity).toFixed(8)}));}
 async submitOrder(input:PaperOrderRequest):Promise<BrokerOrder>{const time=this.timestamp();const order:BrokerOrder={remoteOrderId:randomUUID(),...input,filledQuantity:"0",status:"accepted",submittedAt:time,updatedAt:time};this.orders.set(input.clientOrderId,order);if(this.lost){this.lost=false;throw new BrokerProviderError("timeout","fixture lost response",true,true);}return order;}
 async cancelOrder(remoteOrderId:string){this.cancelPending.add(remoteOrderId);}
 acknowledgeCancel(remoteOrderId:string){const order=this.byRemote(remoteOrderId);if(order.status==="filled")return order;const next={...order,status:"canceled"as const,updatedAt:this.timestamp()};this.orders.set(order.clientOrderId,next);return next;}
 async getOrderByClientOrderId(clientOrderId:string){return this.orders.get(clientOrderId);}
 async listOpenOrders(){return[...this.orders.values()].filter(o=>!["filled","canceled","rejected","expired"].includes(o.status));}
 async listActivities(after?:string){const index=after?this.activities.findIndex(a=>a.remoteActivityId===after):-1;return this.activities.slice(index+1);}
 partialFill(remoteOrderId:string,quantity:string,price:string){return this.applyFill(remoteOrderId,quantity,price,false);}fill(remoteOrderId:string,quantity:string,price:string){return this.applyFill(remoteOrderId,quantity,price,true);}
 private applyFill(remoteOrderId:string,quantity:string,price:string,complete:boolean){const order=this.byRemote(remoteOrderId);const qty=Number(quantity),amount=qty*Number(price),current=this.positions.get(order.symbol)??{quantity:0,cost:0};const direction=order.side==="buy"?1:-1;this.positions.set(order.symbol,{quantity:current.quantity+direction*qty,cost:current.cost+direction*amount});this.cash-=direction*amount;const filled=Number(order.filledQuantity)+qty;const next={...order,filledQuantity:String(filled),filledAveragePrice:price,status:complete?"filled"as const:"partially_filled"as const,updatedAt:this.timestamp()};this.orders.set(order.clientOrderId,next);this.activities.push({remoteActivityId:randomUUID(),type:"FILL",occurredAt:next.updatedAt,symbol:order.symbol,quantity,price,side:order.side,remoteOrderId,raw:{fixture:true}});return next;}
 private byRemote(id:string){const order=[...this.orders.values()].find(o=>o.remoteOrderId===id);if(!order)throw new Error("FIXTURE_ORDER_NOT_FOUND");return order;}
}
